# Generated by Django 5.1.5 on 2025-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metamask_nonce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='metamask_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
