# Generated by Django 5.1.5 on 2025-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_metamask_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tonkeeper_address',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
