# Generated by Django 5.1.5 on 2025-02-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_tonkeeper_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tron_nonce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tron_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
